### ISSUE TITLE
Suggestions about communication protocol

### ISSUE THREAD

**Issue by patrickelectric** [tudsat-rocket/sam#8]
Hi and nice software! 

Is there a way to integrate it with zenoh / dds or mavlink messages somehow ?

**Comment by KoffeinFlummi** [comment]
Thanks! We use a custom protocol to communicate between our ground station and our rocket (https://github.com/tudsat-rocket/mithril/blob/main/src/telemetry.rs#L281). These packets are then reassembled into a series of vehicle states (https://github.com/tudsat-rocket/sam/blob/main/src/state.rs#L8, although in the future we will probably use a similar type from the firmware instead), which are then plotted/displayed.

In theory, you could implement a custom data source (https://github.com/tudsat-rocket/sam/tree/main/src/data_source) for MavLink via UDP or Zenoh (which I hadn't heard of actually, and it looks very interesting), but since much of the software is specifically catered towards our needs, or at least for similar high-powered rockets, it would probably not be worth the effort (I'm assuming you are more interested in stuff like UAVs).

I think you could definitely reuse components for other egui-based ground station software though. I have a half-started prototype of an egui drone ground station laying around on my hard drive, and I think parts of this software could probably be split off into other crates (I have been meaning to implement our MapBox tile source into https://github.com/podusowski/walkers, for instance), or upstreamed back into egui, like plot following functionality.

Feel free to join our Discord btw, in case you want to chat: https://discord.gg/9wDMa2hA

**Comment by IhsenBouallegue** [comment]
@patrickelectric If you are looking into building a rust based Ground Station for UAVs, I am very interested and would love to help! Join our discord or let me know over github. It's time we let QGroundControl retire 😝

**Comment by patrickelectric** [comment]
Hi @KoffeinFlummi,

Thanks for the explanation, I may take a closer look on day when moving to rockets or extraterrestrial robots. I have already conquered land, air and water. I believe that the final frontier will be space for me :laughing:
BTW, the discord link is not working for me. 

@IhsenBouallegue, we are working on a fresh new GCS based on our experience, [cockpit](https://github.com/bluerobotics/cockpit), the frontend was entirely done with web technologies, we have written a software architecture on the frontend that does some of the logic and works over [mavlink2rest](https://github.com/mavlink/mavlink2rest) and [mavlink-camera-manager](https://github.com/mavlink/mavlink-camera-manager). We are now moving moving this "software architecture" to be entirely done on rust with a microservice architecture using zenoh as our alternative to dds/ros.

**Comment by IhsenBouallegue** [comment]
@patrickelectric that's a really awesome project! Will look if I can contribute anything 😃

**Comment by KoffeinFlummi** [comment]
@patrickelectric That does sound interesting! The discord server registered you joining, so it might be an account mixup.
